### PR TITLE
add db schema for Song table and association with User

### PR DESCRIPTION
**Pull request by TomxLi**
initial addition, verified in mysql that UserID is part of Songs

### CODE REVIEW

**Review by bryson-palmer — CHANGES_REQUESTED** [review]
Great job! On getting this piece of the puzzle in. 

Could you please change the `allowNull` to true for (tempo, key, chords, and lyrics)? 
I was thinking that as a User I might not have that information right at that moment and wouldn't want them to get stuck in the process. They will be able to update the song page later and add in the pieces at that time or even by piecemeal. Thanks.

**Comment by bryson-palmer** [comment]
I wanted to add to the above changes that we should have some additional validations for some columns. 

Could you please add these validations to the tempo column:
min: 60 
max: 200
isNumber: true
That way a user can't enter 1000 for a tempo or symbols or letters :0 
Please make sure that the data type.INTEGER.

Also, for the key of the song I want to make sure that it can't be a number:
isNumber: false.
Data type.STRING

artist, song, and chords should be data type.STRING

lyrics should be data type.text

I believe that is accurate. Please let me know if I got those wrong. I think with the correct data types and validations, this file will be in good order.

**Comment by TomxLi** [comment]
> Great job! On getting this piece of the puzzle in.
> 
> Could you please change the `allowNull` to true for (tempo, key, chords, and lyrics)?
> I was thinking that as a User I might not have that information right at that moment and wouldn't want them to get stuck in the process. They will be able to update the song page later and add in the pieces at that time or even by piecemeal. Thanks.

removed allowNull validation for these columns, as setting it to be true will only allow null.

**Comment by TomxLi** [comment]
> I wanted to add to the above changes that we should have some additional validations for some columns.
> 
> Could you please add these validations to the tempo column:
> min: 60
> max: 200
> isNumber: true
> That way a user can't enter 1000 for a tempo or symbols or letters :0
> Please make sure that the data type.INTEGER.
> 
> Also, for the key of the song I want to make sure that it can't be a number:
> isNumber: false.
> Data type.STRING
> 
> artist, song, and chords should be data type.STRING
> 
> lyrics should be data type.text
> 
> I believe that is accurate. Please let me know if I got those wrong. I think with the correct data types and validations, this file will be in good order.

Fixed, datatype to text for lyrics.

**Review by bryson-palmer — COMMENTED** [review]
Changes accepted.

**Pull request closed without merging**
